name: radio_garden
description: Radio Garden discord bot.
version: 0.0.1
homepage: https://github.com/tomassasovsky/radio_garden
repository: https://github.com/tomassasovsky/radio_garden
documentation: https://github.com/tomassasovsky/radio_garden
issue_tracker: https://github.com/tomassasovsky/radio_garden/issues
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  dotenv: ^4.0.1
  duration: ^3.0.12
  fuzzysearch: ^0.1.3
  http: ^0.13.5
  human_duration_parser: ^2.0.1
  logging: ^1.1.0
  mason_logger: ^0.2.0
  nyxx: ^4.1.3
  nyxx_commands: ^4.3.0
  nyxx_interactions: ^4.3.2
  nyxx_lavalink: ^3.1.0
  prometheus_client: ^1.0.0+1
  prometheus_client_shelf: ^1.0.0+1
  pub_updater: ^0.2.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  time_ago_provider: ^4.2.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

assets:
  - .env/
