name: radio_garden
description: Radio Garden discord bot.
version: 0.0.1
homepage: https://github.com/tomassasovsky/radio_garden
repository: https://github.com/tomassasovsky/radio_garden
documentation: https://github.com/tomassasovsky/radio_garden
issue_tracker: https://github.com/tomassasovsky/radio_garden/issues
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dotenv: ^4.0.1
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  logging: ^1.1.0
  nyxx: ^4.2.1
  nyxx_commands: ^4.3.0
  nyxx_interactions: ^4.4.0
  nyxx_lavalink: ^3.1.0
  prometheus_client: ^1.0.0+1
  prometheus_client_shelf: ^1.0.0+1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  time_ago_provider: ^4.2.0
  uuid: ^3.0.7
  usage: ^4.1.0

dev_dependencies:
  build_runner: ^2.3.2
  build_verify: ^3.0.0
  build_version: ^2.1.1
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0

dependency_overrides:
  analyzer: ^4.6.0

assets:
  - .env/
